//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ciudad
    {
        public ciudad()
        {
            this.proveedor = new HashSet<proveedor>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string codigo_departamento { get; set; }
        
        [JsonIgnore]
        public virtual departamento departamento { get; set; }
        [JsonIgnore]
        public virtual ICollection<proveedor> proveedor { get; set; }
    }
}
