//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class compatibilidad
    {
        public int id_compatibilidad { get; set; }
        public Nullable<int> codigo_repuesto { get; set; }
        public string id_marca { get; set; }
        public Nullable<int> cantidad_requerida { get; set; }
        
        [JsonIgnore]
        public virtual repuesto repuesto { get; set; }
        [JsonIgnore]
        public virtual marca marca { get; set; }
    }
}
