//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTallerMotosEntities : DbContext
    {
        public DBTallerMotosEntities()
            : base("name=DBTallerMotosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categorias { get; set; }
        public DbSet<ciudad> ciudads { get; set; }
        public DbSet<cliente> clientes { get; set; }
        public DbSet<compatibilidad> compatibilidads { get; set; }
        public DbSet<departamento> departamentoes { get; set; }
        public DbSet<empleado> empleadoes { get; set; }
        public DbSet<garantia> garantias { get; set; }
        public DbSet<marca> marcas { get; set; }
        public DbSet<moto> motoes { get; set; }
        public DbSet<proveedor> proveedors { get; set; }
        public DbSet<repuesto> repuestoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tipo_empleado> tipo_empleado { get; set; }
        public DbSet<venta> ventas { get; set; }
    }
}
