//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTallerMotosEntities : DbContext
    {
        public DBTallerMotosEntities()
            : base("name=DBTallerMotosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categoria { get; set; }
        public DbSet<ciudad> ciudad { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<compatibilidad> compatibilidad { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<garantia> garantia { get; set; }
        public DbSet<marca> marca { get; set; }
        public DbSet<moto> moto { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<repuesto> repuesto { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipo_empleado> tipo_empleado { get; set; }
        public DbSet<venta> venta { get; set; }
    }
}
