//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class garantia
    {
        public int codigo_garantia { get; set; }
        public Nullable<int> codigo_venta { get; set; }
        public Nullable<int> duracion { get; set; }
    
        [JsonIgnore]
        public virtual venta venta { get; set; }
    }
}
