//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moto
    {
        public moto()
        {
            this.clientes = new HashSet<cliente>();
        }
    
        public string id_moto { get; set; }
        public string Marca { get; set; }
        public string modelo { get; set; }
        public string Año { get; set; }
    
        public virtual ICollection<cliente> clientes { get; set; }
    }
}
