//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio_Respuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_empleado
    {
        public tipo_empleado()
        {
            this.empleadoes = new HashSet<empleado>();
        }
    
        public string codigo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<empleado> empleadoes { get; set; }
    }
}
